services:
  postgres:
    image: postgres:16-alpine
    container_name: dailysql-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: dailysql-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
